name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install tox and any other packages for test
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: tox -e flake8
