name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - python: "3.7"
          toxenv: py37
        - python: "3.8"
          toxenv: py38
        - python: "3.9"
          toxenv: py39
        - python: "3.10"
          toxenv: py310
        - python: "3.10"
          toxenv: sphinx-dev

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Check Python version
      run: python --version
    - name: Install dependencies
      run: pip install -U tox
    - name: Run Tox
      run: tox -e ${{ matrix.toxenv }} -- -vv
